### ISSUE TITLE
Inquiry on the dataset

### ISSUE THREAD

**Issue by gentaiscool** [fajri91/sum_liputan6#1]
Hi Fajri, thank you for the excellent work!
I wondered when you would release the dataset. 
I would be happy to explore your latest dataset.

I am looking forward to your reply.

**Comment by fajri91** [comment]
Hi @gentaiscool, 

Thank you for your inquiry, we are working on that at moment, targeting to release the dataset at least before AACL conference date. 

Thank you.

**Comment by gentaiscool** [comment]
Sounds great! Thanks
