### ISSUE TITLE
Broken Link in `url.json`

### ISSUE THREAD

**Issue by andreaschandra** [fajri91/sum_liputan6#3]
Hi,

I found a broken link https://www.liputan6.com/news/read/130420/jamiyatul-islamiyah-sesat- in `url.json` in `train_urls`
when I checked manually, it redirect to liputan6 homepage

**Comment by fajri91** [comment]
Hi, 

It is possibly because the news is already removed from Liputan6 database. I will adjust the code for handling this special case. 
The best way to obtain the corpus is by filling in the form.

Fajri
